sudo: false
language: node_js
node_js:
  - '0.10'
  - '0.12'
matrix:
  allow_failures:
    - node_js: 'node_js'
  fast_finish: true
script: npm test --coverage
after_script: codeclimate < coverage/lcov.info
